### ISSUE TITLE
ffmpeg 5.0 is now available

### ISSUE THREAD

**Issue by nobodyatandnothing** [marioroy/ffmpeg-on-clear-linux#11]

**Comment by marioroy** [comment]
For context, Firefox does not yet support FFmpeg 5.0 at this time.

Someone put a request at bugzilla.
[Implement support for FFmpeg 5.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1750760)

**Comment by nobodyatandnothing** [comment]
it seems that this has now been fixed and will be available is firefox 99

**Comment by marioroy** [comment]
When that time comes, `firefox --version` works to check if Firefox 99 or later is installed.  Otherwise, keep using FFmpeg 4.4.

**Comment by nobodyatandnothing** [comment]
do chromium based browsers work with ffmpeg 5.0 ?

**Comment by marioroy** [comment]
While playing a video, none use the external FFmpeg libraries from checking `lsof` output. Google Chrome and derivatives likely use a [third_party](https://chromium.googlesource.com/chromium/third_party/) copy of FFmpeg built with the browser. Vivaldi uses a shared FFmpeg library in /opt/vivaldi/lib/.

Fortunately, Brave, Google Chrome, and Vivaldi use the external vdpau/nvidia VA-API driver if available.

**Comment by marioroy** [comment]
I tested Firefox 99.0 with FFmpeg 5.0.1. Hardware decode acceleration is broken using NVIDIA graphics. Mentioned [here](https://github.com/elFarto/nvidia-vaapi-driver/issues/66) (bottom of page), the fix came too late for them to include it in the 99.0 release.

**Comment by marioroy** [comment]
Completed in commit [a59fbda](https://github.com/marioroy/ffmpeg-on-clear-linux/commit/a59fbdaeadaa8e98dbe5f6a3b75d47efd20977e0).
