### ISSUE TITLE
Fail to build FFmpeg

### ISSUE THREAD

**Issue by marcusobrien** [marioroy/ffmpeg-on-clear-linux#16]
Hi,

I get the same error as listed in a previous incident 

https://github.com/marioroy/ffmpeg-on-clear-linux/issues/7

The error is 
fmpeg/libpostproc/version.h
ERROR: gnutls not found using pkg-config

Just seeing if its something I have done, and will add comments.

**Comment by nobodyatandnothing** [comment]
`sudo swupd bundle-add devpkg-gnutls`
