### ISSUE TITLE
why is there a script to build opus if there is a bundle 'devpkg-opus'?

### ISSUE THREAD

**Issue by nobodyatandnothing** [marioroy/ffmpeg-on-clear-linux#18]

**Comment by marioroy** [comment]
Devpkg bundles are added all the time in Clear Linux. Devpkg-opus did not exist when the repo was made.

**Comment by marioroy** [comment]
The `devpkg-opus` is in the `000-install-dependencies`.  I will remove opus bits from /usr/local and try building FFmpeg.

**Comment by marioroy** [comment]
This is resolved in [commit e84a378](https://github.com/marioroy/ffmpeg-on-clear-linux/commit/e84a378468c158d7ad14f76667debbfd5c0cb7a2).
