### ISSUE TITLE
why is layers.omtp.enable included ?

### ISSUE THREAD

**Issue by nobodyatandnothing** [marioroy/ffmpeg-on-clear-linux#4]
layers.omtp.enable has no effect when webrender is on

**Comment by marioroy** [comment]
This setting was added recently. I came across ```layers.omtp.enable``` on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1482469). Darkspirit states the setting is already enabled. At the time included the setting in the event disabled. I wanted to look into this more but got side tracked with life.

**Comment by marioroy** [comment]
The ```layers.omtp.enable``` setting doesn't appear in recent Firefox builds. I removed the setting from the README file.
