### ISSUE TITLE
ERROR: gnutls not found using pkg-config

### ISSUE THREAD

**Issue by KaeLL** [marioroy/ffmpeg-on-clear-linux#7]
```
Launching 700-build-ffmpeg-cuda...

Launching 710-build-ffmpeg-nocuda...
building ffmpeg branch release/4.4
git clone --depth 1 --branch release/4.4 https://git.ffmpeg.org/ffmpeg.git
Cloning into 'ffmpeg'...
remote: Enumerating objects: 7425, done.
remote: Counting objects: 100% (7425/7425), done.
remote: Compressing objects: 100% (6401/6401), done.
remote: Total 7425 (delta 1907), reused 3596 (delta 732)
Receiving objects: 100% (7425/7425), 15.88 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (1907/1907), done.
ERROR: gnutls not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

**Comment by KaeLL** [comment]
After installing these packages:
```
devpkg-gnutls devpkg-libass devpkg-libdrm devpkg-mediasdk devpkg-pulseaudio devpkg-librsvg devpkg-speex devpkg-libtheora devpkg-v4l-utils devpkg-libvorbis devpkg-libvpx devpkg-libwebp devpkg-libxml2 devpkg-libgcrypt devpkg-SDL2
```
and running `sudo ./710-build-ffmpeg-nocuda` again, I get
```
building ffmpeg branch release/4.4
ERROR: vaapi requested but not found
```
which swupd search recommends the `software-defined-cockpit` package, but even after installing it, the error still won't go away.

**Comment by marioroy** [comment]
Thanks for the report. Interestingly, ```devpkg-gnutls``` is in [000-install-dependencies](https://github.com/marioroy/ffmpeg-on-clear-linux/blob/main/scripts/000-install-dependencies), line 13. By chance, did you run ```000-install-dependencies```? It has all the packages you mentioned and much more.

Running ```710-build-ffmpeg-nocuda``` is working for me.

**Comment by marioroy** [comment]
You need the ```devpkg-libva``` package.

**Comment by KaeLL** [comment]
I ran the `build-all` recipe initially **and** it broke. Seeing that it broke in the last stage, I then proceeded to install the devpkg packages manually and rerun the last stage manually, up until I reaching the vaapi dependency as mentioned.

**Comment by nobodyatandnothing** [comment]
Does `vainfo` work?

**Comment by KaeLL** [comment]
<details>
<summary>I think so</summary>

```
$ vainfo 
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva error: /usr/lib64/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
```

</details>

So yeah, after installing the list of packages mentioned above, and `devpkg-libva`, the installation finished correctly. How can I make sure it worked (as in, how to test it other than just opening youtube videos)?

**Comment by nobodyatandnothing** [comment]
1. check about:support page in firefox
2. install the igt-gpu-tools bundle and use `sudo intel_gpu_top` to  check if "Video" section percentage goes up while watching a video
3. install the igt-gpu-tools bundle and use `watch -n 1 sudo intel_gpu_frequency` to check if the frequency goes up when watching a video

**Comment by marioroy** [comment]
@KaeLL, for your setup, set the environment variable ```LIBVA_DRIVER_NAME=i965``` in ```~/.config/firefox.conf```.

```bash
$ LIBVA_DRIVER_NAME=i965 vainfo
```

How can I make sure it worked? For others to see, the following is info from @nobodyatandnothing.

1. check about:support page in firefox
2. install the igt-gpu-tools bundle and use ```sudo intel_gpu_top``` to check if "Video" section percentage goes up while watching a video
3. install the igt-gpu-tools bundle and use ```watch -n 1 sudo intel_gpu_frequency``` to check if the frequency goes up when watching a video

**Comment by nobodyatandnothing** [comment]
you can check that you have ffmpeg installed by seeing if you have the command `ffmpeg`

**Comment by marcusobrien** [comment]
Hi, 

I get the same error when building ffmpeg after following the guide.

fmpeg/libpostproc/version.h
ERROR: gnutls not found using pkg-config

Then when I try the recommendation above to install devpkg-libva, it fails as it cant find it. 

sudo apt-get install devpkg-libva

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package devpkg-libva

I have already updated apt-get eg 

sudo apt-get update
