### ISSUE TITLE
Difference between patchset and xtknight/vdpau-va-driver-vp9

### ISSUE THREAD

**Issue by Mazotis** [marioroy/ffmpeg-on-clear-linux#9]
I used the version of the VP9 VDPAU driver found at https://github.com/xtknight/vdpau-va-driver-vp9 in the past.
I was wondering if the patchset here differ from that code base ?

**Comment by marioroy** [comment]
When I first made this, the archive from Debian contained bug fixes. I'm looking into this. An update is in the works.

**Comment by marioroy** [comment]
The author may be busy, but isn't responding to a recent PR. I'm going to hold off at this time. Currently, Firefox is able to decode vp9 videos. This [repo](https://github.com/xuanruiqi/vdpau-va-driver-vp9) is 2 commits ahead of xtknight:master.

**Comment by marioroy** [comment]
Arch Linux switched to [xuanruiqi](https://github.com/xuanruiqi/vdpau-va-driver-vp9) branch on [2021-10-13](https://aur.archlinux.org/cgit/aur.git/log/?h=libva-vdpau-driver-vp9-git). I will update the 130 script to pull from this branch as well.

**Comment by marioroy** [comment]
This is completed.

* 7145c1e Use xuanruiqi branch in build-vdpau-driver script
* 37c59b6 Rename 130 script to 130-build-vdpau-va-driver-v9
* ac034a0 Update README, remove patches folder
